version: '3'

services:
  frontend:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-frontend:latest
    container_name: frontend
    environment:
      # Define empty VITE_BACKEND_URL because it's production
      - VITE_BACKEND_URL=http://localhost:4400
      # Define empty VITE_BACKEND_SOCKET_URL so it will default to window.location.host
      - VITE_BACKEND_SOCKET_URL=http://localhost:4400
      - VITE_AZURE_BACKEND_URL=http://localhost:4400
      - MODE=development
    ports:
      - "5173:5173"
    restart: always

  backend:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: "mongodb://mongo:27017/evaluetonsavoir"
      MONGO_DATABASE: evaluetonsavoir
      # EMAIL_SERVICE: gmail
      # SENDER_EMAIL: infoevaluetonsavoir@gmail.com
      # EMAIL_PSW: 'vvml wmfr dkzb vjzb'
      JWT_SECRET: haQdgd2jp09qb897GeBZyJetC8ECSpbFJe
      SITE_URL: http://localhost
      # OIDC_URL: https://evalsa.etsmtl.ca
      FRONTEND_PORT: 5173
      # FRONTEND_URL: "http://localhost:5173"
      AUTHENTICATED_ROOMS: false
    volumes:
      - /opt/EvalueTonSavoir/auth_config.json:/usr/src/app/serveur/auth_config.json
    depends_on:
      - mongo
      - keycloak
    restart: always

  # Ce conteneur sert de routeur pour assurer le bon fonctionnement de l'application
  nginx:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-router:latest
    container_name: nginx
    ports: 
      - "80:80"
    depends_on:
       - backend
       - frontend
    restart: always

  # Ce conteneur est la base de données principale pour l'application
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    tty: true
    volumes:
      - mongodb_data:/data/db
    restart: always

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HEALTH_ENABLED: 'true'
      KC_FEATURES: preview
    ports:
      - "8080:8080"
    volumes:
      - /opt/EvalueTonSavoir/oauth-tester/config.json:/opt/keycloak/data/import/realm-config.json   
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false

volumes:
  mongodb_data:
    external: false