services:

  frontend:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:3000}
    networks:
      - quiz_network
    restart: always

  backend:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT:-3000}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/evaluetonsavoir}
      MONGO_DATABASE: ${MONGO_DATABASE:-evaluetonsavoir}
      EMAIL_SERVICE: ${EMAIL_SERVICE:-gmail}
      SENDER_EMAIL: ${SENDER_EMAIL:-infoevaluetonsavoir@gmail.com}
      EMAIL_PSW: ${EMAIL_PSW:-'vvml wmfr dkzb vjzb'}
      JWT_SECRET: ${JWT_SECRET:-haQdgd2jp09qb897GeBZyJetC8ECSpbFJe}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      SESSION_Secret: ${SESSION_Secret:-'lookMomImQuizzing'}
      SITE_URL: ${SITE_URL:-http://localhost}
      FRONTEND_PORT: ${FRONTEND_PORT:-5173}
      USE_PORTS: ${USE_PORTS:-false}
      AUTHENTICATED_ROOMS: ${AUTHENTICATED_ROOMS:-false}
      QUIZROOM_IMAGE: ${QUIZROOM_IMAGE:-ghrc.io/fuhrmanator/evaluetonsavoir-quizroom:latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./auth_config.json:/usr/src/app/serveur/auth_config.json
    networks:
      - quiz_network
    restart: always

  quizroom:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-quizroom:latest
    container_name: quizroom
    ports:
      - "4500:4500"
    depends_on:
      - backend
    networks:
      - quiz_network
    restart: always

  nginx:
    image: ghcr.io/ets-cfuhrman-pfe/evaluetonsavoir-router:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - quiz_network
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Montreal
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 5 * * * # At 5 am everyday
    restart: always

networks:
  quiz_network:
    name: evaluetonsavoir_quiz_network
    driver: bridge