---
  - name: Déployer des services avec Docker Compose
    hosts: local
    tasks:
      - name: Installer les dépendances de compilation et curl
        ansible.builtin.package:
          name: 
            - python3-venv
            - curl
          state: present
        become: true
  
      - name: Télécharger Docker Compose plugin
        ansible.builtin.get_url:
          url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
          dest: /usr/local/lib/docker/cli-plugins/docker-compose
          mode: '0755'
        become: true
  
      - name: Vérifier l'installation de Docker Compose plugin
        ansible.builtin.command:
          cmd: docker compose version
  
      - name: Lancer Docker Compose
        ansible.builtin.shell: |
          docker compose -f /mnt/c/Users/Jerry/Profile/ETS/Session_16_A24/PFE_LOG795/EvalueTonSavoir/docker-compose.yaml up -d
        args:
          chdir: "/mnt/c/Users/Jerry/Profile/ETS/Session_16_A24/PFE_LOG795/EvalueTonSavoir"
        become: true
  
  

# ---
# - name: Déployer l'application Docker Compose
#   hosts: local
#   tasks:
#     - name: S'assurer que Docker est installé
#       win_package:
#         name: Docker Desktop
#         state: present

#     - name: S'assurer que Docker Compose est installé
#       win_package:
#         name: docker-compose
#         state: present

#     - name: Démarrer les conteneurs Docker
#       docker_compose:
#         project_src: 
#         restarted: yes
#         build: yes

# ---
# - name: Déployer des services avec Docker Compose
#   hosts: local
#   tasks:
#     - name: Lancer Docker Compose
#       community.docker.docker_compose:
#         project_src: 
#         state: present  # "present" pour construire et démarrer les services