site_name: EvalueTonSavoir

theme:
  name: material
  features:
  - content.code.copy
  - content.code.select
  - content.code.annotate
  locale: fr
  highlightjs: true
  hljs_languages:
  - javascript
  - typescript
  - css
  - react
  - yaml
  - latex
  - katex
  - gift

use_directory_urls: false

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences