name: Creates docs and deploy to gh-pages
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env:
      PUMLURL: "https://www.plantuml.com/plantuml/"
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        working-directory: ./documentation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build docs
        working-directory: ./documentation
        run:  mkdocs build --verbose --clean

      - name: Push docs to gh-pages
        working-directory: ./documentation
        run:  python deploy.py